version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/

      - run:
          name: Authenticate Docker to ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 450460062983.dkr.ecr.us-east-1.amazonaws.com

      - run:
          name: Build Docker image
          command: docker build -t flask-app .

      - run:
          name: Tag image
          command: docker tag flask-app:latest 450460062983.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - run:
          name: Push image to ECR
          command: docker push 450460062983.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - run:
          name: Configure kubeconfig for EKS
          command: aws eks update-kubeconfig --region $us-east-1 $eks-cluster

      - run:
          name: Deploy to EKS
          command: kubectl apply -f k8s/

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - build-and-deploy

