version: 2.1

jobs:
  build-and-deploy:
    machine: true
    environment:
      AWS_REGION: us-east-1
      ECR_URL: 450460062983.dkr.ecr.us-east-1.amazonaws.com
      EKS_CLUSTER: eks-cluster  # Replace with your actual EKS cluster name

    steps:
      - checkout

      - run:
          name: Install AWS CLI and kubectl
          command: |
            sudo apt update
            sudo apt install -y unzip curl apt-transport-https gnupg
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
            aws --version

            # Install kubectl
            curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --client

      - run:
          name: Authenticate Docker to ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 450460062983.dkr.ecr.us-east-1.amazonaws.com

      - run:
          name: Build Docker image
          command: docker build -t flask-app .

      - run:
          name: Tag Docker image
          command: docker tag flask-app:latest 450460062983.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - run:
          name: Push Docker image to ECR
          command: docker push 450460062983.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - run:
          name: Configure kubectl for EKS
          command: |
            aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
            kubectl get nodes

      - run:
          name: Deploy to EKS
          command: kubectl apply -f k8s/

workflows:
  deploy-workflow:
    jobs:
      - build-and-deploy




